# Generated by Django 4.1.2 on 2023-09-27 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('den', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('problems', models.TextField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('priority', models.CharField(choices=[('Низкий', 'Низкий'), ('Средний', 'Средний'), ('Высокий', 'Высокий')], default='Низкий', max_length=20)),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='NEW', max_length=20)),
            ],
            options={
                'verbose_name': 'User_name',
                'verbose_name_plural': 'User_names',
            },
        ),
        migrations.AlterField(
            model_name='action',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action', to='den.problem'),
        ),
        migrations.DeleteModel(
            name='User_name',
        ),
    ]
