# Generated by Django 4.1.2 on 2023-09-27 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('den', '0002_problem_alter_action_user_name_delete_user_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'verbose_name': 'Problem', 'verbose_name_plural': 'Problems'},
        ),
    ]
